packages:
  - name: builder
    shared: true
    actions:
      - name: build_go_1.12
        runtime: "go:1.12"
        limits:
          timeout: ${TIMEOUT}
          memory: 768
      - name: build_go_1.15
        runtime: "go:1.15"
        limits:
          timeout: ${TIMEOUT}
          memory: 768
      - name: build_java_8
        runtime: "java:8"
        limits:
          timeout: ${TIMEOUT}
          memory: 768
      - name: build_php_7.3
        runtime: "php:7.3"
        limits:
          timeout: ${TIMEOUT}
          memory: 768
      - name: build_php_8.0
        runtime: "php:8.0"
        limits:
          timeout: ${TIMEOUT}
          memory: 768
      - name: build_python_2
        runtime: "python:2"
        limits:
          timeout: ${TIMEOUT}
          memory: 768
      - name: build_python_3
        runtime: "python:3"
        limits:
          timeout: ${TIMEOUT}
          memory: 768
      - name: build_python_3ai
        runtime: "python:3ai"
        limits:
          timeout: ${TIMEOUT}
          memory: 768
      - name: build_ruby_2.6
        runtime: "ruby:2.6"
        limits:
          timeout: ${TIMEOUT}
          memory: 768
      - name: build_rust_1.34
        runtime: "rust:1.34"
        limits:
          timeout: ${TIMEOUT}
          memory: 768
      - name: build_swift_4
        runtime: "swift:4"
        limits:
          timeout: ${TIMEOUT}
          memory: 768
      - name: build_swift_5.4
        runtime: "swift:5.4"
        limits:
          timeout: ${TIMEOUT}
